name: Zig Build, Lint and Format

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  check-all:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Format check
        run: zig fmt --check .

      - name: Build snake
        run: cd projects/raylib-snake && zig build --summary all

      - name: Setup python
        uses: actions/setup-python@v6

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: Build all
        run: zig build --summary all all

      - name: Lint check
        run: zig build lint
